# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  android: circleci/android@2.3.0
  flutter: circleci/flutter@2.0.2


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:

  build:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - flutter/install_sdk:
          version: 3.7.3
      - checkout
      - run: flutter pub get
      - persist_to_workspace:
          root: .
          paths:
            - .

  unit_test:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - attach_workspace:
          at: .
      - flutter/install_sdk:
          version: 3.7.3
      - run: flutter test test/unit_test.dart

  integration_test:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - attach_workspace:
          at: .
      - flutter/install_sdk:
          version: 3.7.3
      - android/create-avd:
          avd-name: avd
          install: true
          system-image: system-images;android-33;default;x86_64
      - android/start-emulator:
          avd-name: avd
          post-emulator-launch-assemble-command:
      - run: flutter test integration_test/app_test.dart

  build_apk:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - flutter/install_sdk:
            version: 3.7.3
      - run: flutter doctor -v
      - checkout
      - run: flutter pub get
      - run:
          name: build apk file
          command: flutter build apk

workflows:
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - integration_test:
          requires:
            - build




#      - build_flutter:
#          filters:
#            tags:
#              only: /v\.\d+\.\d+\.\d+/
#            branches:
#              ignore: /.*/