version: 2.1

orbs:
  android: circleci/android@2.3.0
  flutter: circleci/flutter@2.0.2

jobs:
  build_app:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - flutter/install_sdk:
          version: 3.7.3
      - checkout
      - run: flutter pub get
      - run: echo $GOOGLE_SERVICES_JSON | base64 -d -o android/app/google-services.json
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_apk:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - attach_workspace:
          at: .
      - flutter/install_sdk:
          version: 3.7.3
      - run: flutter build apk
      - persist_to_workspace:
          root: .
          paths:
            - .

  distribute_apk:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - attach_workspace:
          at: .
      - run: curl -sL https://firebase.tools | bash
      - run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk
         --token "$FIREBASE_TOKEN"
         --app "$FIREBASE_APP_ID_ANDROID"
         --groups "main"

workflows:
  build_and_test:
    jobs:
      - build_app
      - build_apk:
          requires:
            - build_app
      - distribute_apk:
          requires:
            - build_apk