version: 2.1

orbs:
  android: circleci/android@2.3.0
  flutter: circleci/flutter@2.0.2

commands:
  get_flavor:
    description: "Parses flavour from tag"
    parameters:
      tag:
        type: string
        default: ""
    steps:
      - run: FLAVOR=`echo << parameters.tag >> | cut -d'-' -f 3`

jobs:
  build_app:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - flutter/install_sdk:
          version: 3.7.3
      - checkout
      - get_flavor:
          tag: << pipeline.git.tag >>
      - run: echo $FLAVOR
      - run: flutter pub get
      - run: echo $GOOGLE_SERVICES_JSON | base64 -d > android/app/google-services.json
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_apk:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    parameters:
      flavor:
        type: string
    steps:
      - attach_workspace:
          at: .
      - flutter/install_sdk:
          version: 3.7.3
      - get_flavor:
          tag: << pipeline.git.tag >>
      - run: echo $FLAVOR
      - run: flutter build apk
      - persist_to_workspace:
          root: .
          paths:
            - .

  distribute_apk:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - attach_workspace:
          at: .
      - run: curl -sL https://firebase.tools | bash
      - run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk
         --token "$FIREBASE_TOKEN"
         --app "$FIREBASE_APP_ID_ANDROID"
         --groups "main"

workflows:
  build_and_test:
    filters:
      tags:
        only: /v\.\d+\.\d+\.\d+-android-\w+/
      branches:
        ignore: /.*/
    jobs:
      - build_app
      - build_apk:
          requires:
            - build_app
      - distribute_apk:
          requires:
            - build_apk