# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  android: circleci/android@2.3.0
  flutter: circleci/flutter@2.0.2


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:

  build_flutter:
    executor:
      name: android/android-machine
      tag: 2023.05.1
    steps:
      - flutter/install_sdk:
            version: 3.7.0
      - checkout
      - run: flutter doctor -v
      - run: flutter pub get
      - run:
          name: build apk file
          command: flutter build apk

workflows:
  build_flutter:
    jobs:
      - build_flutter